# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          HyungGeun Cho
baseurl:        ""
url:            "https://hyunggeun-cho.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         HyungGeun Cho
  url:          https://hyunggeun-cho.github.io
  email:        chris1503@snu.ac.kr
  github:       HyungGeun-Cho


# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/HyungGeun-Cho/hyunggeun-cho.github.io
